"""
data.py — Base de datos de selecciones y partidos del Mundial 2026
xG y métricas basadas en rendimiento histórico reciente (clasificatorias + torneos 2023-2025).
"""

from __future__ import annotations
from typing import Dict, Any

WC_AVG_XG = 1.18  # promedio xG por equipo por partido, fase de grupos histórica

TACTICAL_FACTORS = {
    "qualified":     {"attack_adj": 0.87, "defense_adj": 1.08},
    "needs_result":  {"attack_adj": 1.08, "defense_adj": 1.00},
    "needs_win":     {"attack_adj": 1.22, "defense_adj": 1.14},
    "eliminated":    {"attack_adj": 0.80, "defense_adj": 1.10},
    "normal":        {"attack_adj": 1.00, "defense_adj": 1.00},
}

# ─── Promedios por confederación (fallback para equipos sin datos propios) ───
CONF_DEFAULTS: Dict[str, Dict[str, Any]] = {
    "UEFA_A":  {"xg_for": 1.68, "xg_against": 0.95, "form_index": 78, "offensive_rating": 82, "defensive_rating": 80},
    "UEFA_B":  {"xg_for": 1.35, "xg_against": 1.12, "form_index": 68, "offensive_rating": 70, "defensive_rating": 70},
    "CONMEBOL_A": {"xg_for": 1.55, "xg_against": 1.00, "form_index": 75, "offensive_rating": 77, "defensive_rating": 76},
    "CONMEBOL_B": {"xg_for": 1.22, "xg_against": 1.25, "form_index": 62, "offensive_rating": 64, "defensive_rating": 62},
    "CONCACAF_A": {"xg_for": 1.30, "xg_against": 1.15, "form_index": 68, "offensive_rating": 70, "defensive_rating": 70},
    "CONCACAF_B": {"xg_for": 1.05, "xg_against": 1.35, "form_index": 55, "offensive_rating": 56, "defensive_rating": 56},
    "CAF_A":   {"xg_for": 1.30, "xg_against": 1.18, "form_index": 65, "offensive_rating": 68, "defensive_rating": 64},
    "CAF_B":   {"xg_for": 1.10, "xg_against": 1.32, "form_index": 55, "offensive_rating": 57, "defensive_rating": 55},
    "AFC_A":   {"xg_for": 1.22, "xg_against": 1.05, "form_index": 68, "offensive_rating": 68, "defensive_rating": 72},
    "AFC_B":   {"xg_for": 1.00, "xg_against": 1.28, "form_index": 55, "offensive_rating": 55, "defensive_rating": 57},
    "OFC":     {"xg_for": 0.92, "xg_against": 1.40, "form_index": 48, "offensive_rating": 48, "defensive_rating": 50},
}

_BASE = {
    "key_injuries": [], "wc_status": "normal", "wc_points": 0,
    "cards_per_game": 2.0, "possession_avg": 50.0, "shots_ot_pg": 4.0,
    "tactical_note": "",
}


def _team(code: str, conf: str, **kw) -> Dict[str, Any]:
    """Constructor de equipo con fallback por confederación."""
    defaults = CONF_DEFAULTS.get(conf, CONF_DEFAULTS["UEFA_B"])
    base = {**_BASE, **defaults}
    base.update(kw)
    return base


TEAMS: Dict[str, Dict[str, Any]] = {
    # ── CONMEBOL ──────────────────────────────────────────────────────────────
    "BRA": _team("BRA", "CONMEBOL_A",
        name="Brasil", group="A",
        xg_for=2.15, xg_against=0.82,
        form_index=84, offensive_rating=91, defensive_rating=87,
        cards_per_game=1.6, possession_avg=59.3, shots_ot_pg=6.4,
        wc_status="qualified", wc_points=6,
        tactical_note="Bloque alto 4-3-3 con extremos desequilibrantes; alta presión sostenida",
    ),
    "ARG": _team("ARG", "CONMEBOL_A",
        name="Argentina", group="A",
        xg_for=1.98, xg_against=0.90,
        form_index=88, offensive_rating=93, defensive_rating=84,
        cards_per_game=2.2, possession_avg=56.5, shots_ot_pg=5.9,
        wc_status="qualified", wc_points=6,
        tactical_note="Transiciones ultrarrápidas desde bloque medio-bajo; líderes emocionales del torneo",
    ),
    "COL": _team("COL", "CONMEBOL_A",
        name="Colombia", group="A",
        xg_for=1.48, xg_against=1.08,
        form_index=72, offensive_rating=76, defensive_rating=74,
        cards_per_game=2.5, possession_avg=51.2, shots_ot_pg=4.2,
        key_injuries=["Extremo derecho (tobillo)", "Mediapunta (muscular)"],
        wc_status="needs_result", wc_points=3,
        tactical_note="4-4-2 compacto, dependiente de la creatividad del mediocampo",
    ),
    "ECU": _team("ECU", "CONMEBOL_B",
        name="Ecuador", group="A",
        xg_for=1.22, xg_against=1.18,
        form_index=61, offensive_rating=65, defensive_rating=63,
        cards_per_game=2.8, possession_avg=47.8, shots_ot_pg=3.5,
        key_injuries=["Delantero centro (muscular)"],
        wc_status="needs_win", wc_points=1,
        tactical_note="Bloque defensivo 5-4-1; altamente dependiente de su delantero referencia",
    ),
    "URU": _team("URU", "CONMEBOL_A",
        name="Uruguay", group="F",
        xg_for=1.38, xg_against=0.92,
        form_index=74, offensive_rating=76, defensive_rating=80,
        cards_per_game=2.2, possession_avg=50.5, shots_ot_pg=4.2,
        wc_status="qualified", wc_points=6,
        tactical_note="Garra charrúa; 4-4-2 sólido con Núñez y Valverde como motor",
    ),
    "CHI": _team("CHI", "CONMEBOL_B",
        name="Chile", group="G",
        xg_for=1.20, xg_against=1.22,
        form_index=60, offensive_rating=63, defensive_rating=61,
        cards_per_game=2.5, possession_avg=50.0, shots_ot_pg=3.6,
        tactical_note="Pressing alto heredado del ciclo Bielsa/Sampaoli, pero generación envejecida",
    ),
    "PER": _team("PER", "CONMEBOL_B",
        name="Perú", group="G",
        xg_for=1.15, xg_against=1.28,
        form_index=57, offensive_rating=60, defensive_rating=58,
        cards_per_game=2.3, possession_avg=49.0, shots_ot_pg=3.4,
        tactical_note="Organización táctica ordenada pero limitado ataque sin Guerrero",
    ),
    "PAR": _team("PAR", "CONMEBOL_B",
        name="Paraguay", group="G",
        xg_for=1.10, xg_against=1.30,
        form_index=54, offensive_rating=57, defensive_rating=57,
        tactical_note="Bloque defensivo pragmático; sin grandes individualidades ofensivas",
    ),
    "BOL": _team("BOL", "CONMEBOL_B",
        name="Bolivia", group="H",
        xg_for=0.95, xg_against=1.55,
        form_index=44, offensive_rating=45, defensive_rating=44,
        tactical_note="Ventaja de altitud en casa; extremadamente limitados a nivel internacional",
    ),
    "VEN": _team("VEN", "CONMEBOL_B",
        name="Venezuela", group="H",
        xg_for=1.18, xg_against=1.25,
        form_index=60, offensive_rating=62, defensive_rating=61,
        tactical_note="Equipo en ascenso; clasificaron por méritos propios por primera vez",
    ),
    # ── UEFA ──────────────────────────────────────────────────────────────────
    "FRA": _team("FRA", "UEFA_A",
        name="Francia", group="B",
        xg_for=1.92, xg_against=0.75,
        form_index=86, offensive_rating=92, defensive_rating=91,
        cards_per_game=1.4, possession_avg=57.8, shots_ot_pg=6.1,
        wc_status="qualified", wc_points=6,
        tactical_note="4-2-3-1 con presión alta y solidez defensiva excepcional; rotará en MD3",
    ),
    "ESP": _team("ESP", "UEFA_A",
        name="España", group="B",
        xg_for=1.78, xg_against=0.72,
        form_index=85, offensive_rating=88, defensive_rating=90,
        cards_per_game=1.8, possession_avg=62.4, shots_ot_pg=5.8,
        wc_status="qualified", wc_points=6,
        tactical_note="Tiki-taka evolucionado; dominio posicional y pressing escalonado de alta efectividad",
    ),
    "ALE": _team("ALE", "UEFA_A",
        name="Alemania", group="C",
        xg_for=1.72, xg_against=1.02,
        form_index=79, offensive_rating=84, defensive_rating=79,
        cards_per_game=1.9, possession_avg=56.8, shots_ot_pg=5.5,
        wc_status="needs_result", wc_points=4,
        tactical_note="4-2-3-1 con pressing alto; vulnerable en contraataques por las bandas",
    ),
    "ING": _team("ING", "UEFA_A",
        name="Inglaterra", group="C",
        xg_for=1.65, xg_against=0.92,
        form_index=80, offensive_rating=83, defensive_rating=82,
        cards_per_game=1.7, possession_avg=55.1, shots_ot_pg=5.3,
        wc_status="qualified", wc_points=6,
        tactical_note="4-3-3 equilibrado con superioridad física; sólido en juego aéreo",
    ),
    "PB": _team("PB", "UEFA_A",
        name="Países Bajos", group="C",
        xg_for=1.58, xg_against=1.05,
        form_index=76, offensive_rating=80, defensive_rating=76,
        cards_per_game=2.0, possession_avg=54.2, shots_ot_pg=5.0,
        wc_status="needs_result", wc_points=3,
        tactical_note="Sistema ofensivo con fragilidad en banda derecha; necesita partido abierto",
    ),
    "BEL": _team("BEL", "UEFA_A",
        name="Bélgica", group="C",
        xg_for=1.45, xg_against=1.18,
        form_index=70, offensive_rating=76, defensive_rating=70,
        cards_per_game=2.3, possession_avg=52.8, shots_ot_pg=4.5,
        key_injuries=["De Bruyne (condición física al 70%)"],
        wc_status="needs_win", wc_points=1,
        tactical_note="Generación de oro en declive físico; abiertos defensivamente en 2do tiempo",
    ),
    "POR": _team("POR", "UEFA_A",
        name="Portugal", group="D",
        xg_for=1.80, xg_against=0.95,
        form_index=83, offensive_rating=87, defensive_rating=82,
        cards_per_game=1.9, possession_avg=55.9, shots_ot_pg=5.7,
        wc_status="qualified", wc_points=6,
        tactical_note="4-3-3 post-Ronaldo consolidado; versatilidad táctica y profundidad de plantilla",
    ),
    "CRO": _team("CRO", "UEFA_A",
        name="Croacia", group="E",
        xg_for=1.32, xg_against=0.90,
        form_index=73, offensive_rating=74, defensive_rating=80,
        cards_per_game=2.0, possession_avg=52.5, shots_ot_pg=4.0,
        wc_status="needs_win", wc_points=1,
        tactical_note="Modric en declive físico pero aún decisivo; organización defensiva de elite",
    ),
    "SUI": _team("SUI", "UEFA_A",
        name="Suiza", group="E",
        xg_for=1.28, xg_against=0.95,
        form_index=72, offensive_rating=72, defensive_rating=78,
        cards_per_game=1.9, possession_avg=52.0, shots_ot_pg=3.9,
        wc_status="qualified", wc_points=5,
        tactical_note="Solidez defensiva como identidad; difícil de batir, limitados en creación",
    ),
    "SRB": _team("SRB", "UEFA_A",
        name="Serbia", group="F",
        xg_for=1.38, xg_against=1.15,
        form_index=68, offensive_rating=72, defensive_rating=68,
        cards_per_game=2.6, possession_avg=50.5, shots_ot_pg=4.2,
        tactical_note="Mitroviç como referencia ofensiva; agresivos pero expuestos defensivamente",
    ),
    "DIN": _team("DIN", "UEFA_A",
        name="Dinamarca", group="F",
        xg_for=1.35, xg_against=0.98,
        form_index=73, offensive_rating=73, defensive_rating=76,
        cards_per_game=1.8, possession_avg=52.5, shots_ot_pg=4.1,
        tactical_note="Equipo colectivo sólido; Eriksen como cerebro organizador del juego",
    ),
    "POL": _team("POL", "UEFA_B",
        name="Polonia", group="I",
        xg_for=1.25, xg_against=1.20,
        form_index=64, offensive_rating=67, defensive_rating=65,
        tactical_note="Lewandowski como único diferencial; colectivo mediocre sin él",
    ),
    "UCR": _team("UCR", "UEFA_B",
        name="Ucrania", group="I",
        xg_for=1.22, xg_against=1.18,
        form_index=62, offensive_rating=64, defensive_rating=64,
        tactical_note="Equipo con motivación extra-deportiva; Zinchenko como líder técnico",
    ),
    "AUT": _team("AUT", "UEFA_B",
        name="Austria", group="J",
        xg_for=1.42, xg_against=1.08,
        form_index=71, offensive_rating=73, defensive_rating=71,
        tactical_note="Equipo en ascenso con buena estructura colectiva; pressing organizado",
    ),
    "TUR": _team("TUR", "UEFA_B",
        name="Turquía", group="J",
        xg_for=1.32, xg_against=1.22,
        form_index=66, offensive_rating=68, defensive_rating=65,
        tactical_note="Calidad individual alta; colectivo inconsistente en partidos decisivos",
    ),
    "ESC": _team("ESC", "UEFA_B",
        name="Escocia", group="K",
        xg_for=1.20, xg_against=1.18,
        form_index=63, offensive_rating=65, defensive_rating=64,
        tactical_note="Intensidad física alta; Robertson como motor en banda izquierda",
    ),
    "ROU": _team("ROU", "UEFA_B",
        name="Rumanía", group="K",
        xg_for=1.15, xg_against=1.25,
        form_index=60, offensive_rating=62, defensive_rating=61,
        tactical_note="Bloque defensivo compacto; contragolpe como principal arma ofensiva",
    ),
    "GEO": _team("GEO", "UEFA_B",
        name="Georgia", group="L",
        xg_for=1.12, xg_against=1.30,
        form_index=59, offensive_rating=61, defensive_rating=59,
        tactical_note="Sorpresa del ciclo; Kvaratskhelia como arma única",
    ),
    "CHE": _team("CHE", "UEFA_B",
        name="Rep. Checa", group="L",
        xg_for=1.18, xg_against=1.22,
        form_index=61, offensive_rating=63, defensive_rating=62,
        tactical_note="Colectivo organizado y difícil de batir; sin grandes individualidades",
    ),
    "SVK": _team("SVK", "UEFA_B",
        name="Eslovaquia", group="L",
        xg_for=1.10, xg_against=1.28,
        form_index=58, offensive_rating=59, defensive_rating=60,
        tactical_note="Bloque defensivo compacto; histórico debut como presencia fija",
    ),
    "ALB": _team("ALB", "UEFA_B",
        name="Albania", group="L",
        xg_for=1.05, xg_against=1.35,
        form_index=55, offensive_rating=56, defensive_rating=56,
        tactical_note="Sorpresa relativa de UEFA; juego directo y presión alta",
    ),
    # ── CONCACAF ──────────────────────────────────────────────────────────────
    "MEX": _team("MEX", "CONCACAF_A",
        name="México", group="D",
        xg_for=1.25, xg_against=1.18,
        form_index=67, offensive_rating=70, defensive_rating=69,
        cards_per_game=2.6, possession_avg=50.8, shots_ot_pg=3.8,
        key_injuries=["Raúl Jiménez (muscular — probable baja)"],
        wc_status="needs_result", wc_points=3,
        tactical_note="Cuestionado mentalmente en presión; pierde xG ofensivo sin su 9 titular",
    ),
    "USA": _team("USA", "CONCACAF_A",
        name="Estados Unidos", group="D",
        xg_for=1.32, xg_against=1.12,
        form_index=70, offensive_rating=72, defensive_rating=73,
        cards_per_game=1.9, possession_avg=52.4, shots_ot_pg=4.1,
        wc_status="needs_win", wc_points=1,
        tactical_note="Joven y atlético; presión alta intensa pero inconsistente en últimos 30 min",
    ),
    "CAN": _team("CAN", "CONCACAF_A",
        name="Canadá", group="D",
        xg_for=1.35, xg_against=1.22,
        form_index=69, offensive_rating=72, defensive_rating=69,
        cards_per_game=2.0, possession_avg=51.5, shots_ot_pg=4.2,
        wc_status="needs_result", wc_points=3,
        tactical_note="Equipo anfitrión motivado; Davies como carta diferencial en 1v1",
    ),
    "HON": _team("HON", "CONCACAF_B",
        name="Honduras", group="K",
        xg_for=1.08, xg_against=1.32,
        form_index=54, offensive_rating=56, defensive_rating=56,
        tactical_note="Regreso histórico al Mundial; intensidad física y juego directo",
    ),
    "CRC": _team("CRC", "CONCACAF_B",
        name="Costa Rica", group="J",
        xg_for=1.10, xg_against=1.28,
        form_index=56, offensive_rating=58, defensive_rating=58,
        tactical_note="Bloque defensivo como principal identidad; desbordantes en set pieces",
    ),
    "PAN": _team("PAN", "CONCACAF_B",
        name="Panamá", group="I",
        xg_for=1.05, xg_against=1.38,
        form_index=52, offensive_rating=54, defensive_rating=54,
        tactical_note="Segunda presencia en el Mundial; físico y ordenado en bloque bajo",
    ),
    "JAM": _team("JAM", "CONCACAF_B",
        name="Jamaica", group="H",
        xg_for=1.02, xg_against=1.42,
        form_index=50, offensive_rating=52, defensive_rating=52,
        tactical_note="Primera vez en un Mundial en décadas; velocidad como única ventaja",
    ),
    # ── CAF ───────────────────────────────────────────────────────────────────
    "MAR": _team("MAR", "CAF_A",
        name="Marruecos", group="B",
        xg_for=1.12, xg_against=0.85,
        form_index=74, offensive_rating=71, defensive_rating=85,
        cards_per_game=2.1, possession_avg=48.5, shots_ot_pg=3.8,
        wc_status="needs_result", wc_points=3,
        tactical_note="Bloque defensivo 5-3-2 con transiciones veloces y set pieces letales",
    ),
    "SEN": _team("SEN", "CAF_A",
        name="Senegal", group="B",
        xg_for=1.28, xg_against=1.15,
        form_index=68, offensive_rating=72, defensive_rating=68,
        cards_per_game=2.4, possession_avg=49.2, shots_ot_pg=3.9,
        key_injuries=["Sadio Mané (tobillo — duda para el partido)"],
        wc_status="needs_win", wc_points=1,
        tactical_note="Sin Mané pierde la referencia ofensiva; colectivo sufre en xG generado",
    ),
    "NIG": _team("NIG", "CAF_A",
        name="Nigeria", group="F",
        xg_for=1.35, xg_against=1.28,
        form_index=65, offensive_rating=71, defensive_rating=63,
        cards_per_game=2.8, possession_avg=49.2, shots_ot_pg=4.1,
        wc_status="needs_result", wc_points=3,
        tactical_note="Individualidades brillantes; colectivo inconsistente con deficiencias defensivas",
    ),
    "CIV": _team("CIV", "CAF_A",
        name="Costa de Marfil", group="G",
        xg_for=1.30, xg_against=1.20,
        form_index=66, offensive_rating=69, defensive_rating=65,
        tactical_note="Campeones AFCON 2024; Drogba-generation reemplazada con nueva generación",
    ),
    "CMR": _team("CMR", "CAF_A",
        name="Camerún", group="H",
        xg_for=1.25, xg_against=1.22,
        form_index=63, offensive_rating=66, defensive_rating=63,
        tactical_note="Los Leones Indomables; físicos y directos, Aboubakar como referencia",
    ),
    "GHA": _team("GHA", "CAF_B",
        name="Ghana", group="I",
        xg_for=1.18, xg_against=1.32,
        form_index=60, offensive_rating=62, defensive_rating=59,
        tactical_note="Generación joven con individualidades; sin estructura colectiva sólida",
    ),
    "EGY": _team("EGY", "CAF_A",
        name="Egipto", group="J",
        xg_for=1.22, xg_against=1.15,
        form_index=64, offensive_rating=65, defensive_rating=65,
        tactical_note="Salah como único diferencial real; sin él el equipo pierde identidad",
    ),
    "DZA": _team("DZA", "CAF_A",
        name="Argelia", group="K",
        xg_for=1.20, xg_against=1.20,
        form_index=62, offensive_rating=63, defensive_rating=63,
        tactical_note="Regreso al Mundial; equipo técnico pero sin grandes estrellas actuales",
    ),
    "TUN": _team("TUN", "CAF_B",
        name="Túnez", group="L",
        xg_for=1.12, xg_against=1.28,
        form_index=58, offensive_rating=60, defensive_rating=59,
        tactical_note="Bloque defensivo ordenado; limitado en creación de xG por las bandas",
    ),
    "MLI": _team("MLI", "CAF_B",
        name="Malí", group="L",
        xg_for=1.10, xg_against=1.35,
        form_index=56, offensive_rating=58, defensive_rating=57,
        tactical_note="Debut en el Mundial; físicos y motivados, limitados tácticamente",
    ),
    "COD": _team("COD", "CAF_B",
        name="RD Congo", group="H",
        xg_for=1.08, xg_against=1.38,
        form_index=54, offensive_rating=56, defensive_rating=55,
        tactical_note="Histórico debut; recursos físicos superiores pero sin cohesión táctica",
    ),
    "RSA": _team("RSA", "CAF_B",
        name="Sudáfrica", group="G",
        xg_for=1.05, xg_against=1.32,
        form_index=53, offensive_rating=54, defensive_rating=56,
        tactical_note="País anfitrión regional; motivados pero con brecha técnica notable",
    ),
    # ── AFC ───────────────────────────────────────────────────────────────────
    "JAP": _team("JAP", "AFC_A",
        name="Japón", group="E",
        xg_for=1.30, xg_against=0.95,
        form_index=76, offensive_rating=74, defensive_rating=80,
        cards_per_game=1.5, possession_avg=53.8, shots_ot_pg=4.3,
        wc_status="qualified", wc_points=6,
        tactical_note="Pressing intenso y disciplina táctica excepcional; mata partidos en velocidad",
    ),
    "COR": _team("COR", "AFC_A",
        name="Corea del Sur", group="E",
        xg_for=1.18, xg_against=1.05,
        form_index=71, offensive_rating=70, defensive_rating=74,
        cards_per_game=1.8, possession_avg=51.2, shots_ot_pg=3.8,
        wc_status="needs_result", wc_points=3,
        tactical_note="Son Heung-min como único diferencial real; colectivo mejorado pero dependiente",
    ),
    "IRN": _team("IRN", "AFC_A",
        name="Irán", group="J",
        xg_for=1.15, xg_against=1.12,
        form_index=65, offensive_rating=66, defensive_rating=67,
        tactical_note="Bloque defensivo 4-1-4-1; Taremi como única referencia ofensiva",
    ),
    "KSA": _team("KSA", "AFC_A",
        name="Arabia Saudita", group="K",
        xg_for=1.05, xg_against=1.28,
        form_index=60, offensive_rating=61, defensive_rating=62,
        tactical_note="Inversión masiva en el fútbol local no se tradujo en mejora inmediata",
    ),
    "AUS": _team("AUS", "AFC_A",
        name="Australia", group="I",
        xg_for=1.18, xg_against=1.15,
        form_index=63, offensive_rating=64, defensive_rating=65,
        tactical_note="Socceroos con buena organización; Leckie como motor en transición",
    ),
    "QAT": _team("QAT", "AFC_B",
        name="Qatar", group="H",
        xg_for=1.00, xg_against=1.42,
        form_index=50, offensive_rating=51, defensive_rating=52,
        tactical_note="Exanfitrión 2022; mejorados respecto a 2022 pero aún inferiores al nivel WC",
    ),
    "UZB": _team("UZB", "AFC_B",
        name="Uzbekistán", group="K",
        xg_for=1.08, xg_against=1.30,
        form_index=56, offensive_rating=58, defensive_rating=58,
        tactical_note="Debut histórico; equipo en ascenso en Asia, físicos y ordenados",
    ),
    "IRQ": _team("IRQ", "AFC_B",
        name="Irak", group="L",
        xg_for=1.05, xg_against=1.35,
        form_index=54, offensive_rating=55, defensive_rating=56,
        tactical_note="Regreso después de décadas; recursos físicos pero sin fineza técnica",
    ),
    # ── OFC ───────────────────────────────────────────────────────────────────
    "NZL": _team("NZL", "OFC",
        name="Nueva Zelanda", group="G",
        xg_for=0.92, xg_against=1.48,
        form_index=46, offensive_rating=47, defensive_rating=49,
        tactical_note="All Whites de vuelta; físicos pero con enorme brecha técnica vs elite",
    ),
    # ── Equipos identificados en el sorteo real ───────────────────────────────
    "NOR": _team("NOR", "UEFA_A",
        name="Noruega", group="I",
        xg_for=1.82, xg_against=0.98,
        form_index=80, offensive_rating=85, defensive_rating=78,
        cards_per_game=1.7, possession_avg=54.0, shots_ot_pg=5.8,
        tactical_note="Haaland como diferencial absoluto; 4-3-3 vertical y directo",
    ),
    "SWE": _team("SWE", "UEFA_A",
        name="Suecia", group="F",
        xg_for=1.42, xg_against=1.05,
        form_index=70, offensive_rating=72, defensive_rating=73,
        cards_per_game=1.9, possession_avg=52.0, shots_ot_pg=4.4,
        tactical_note="4-4-2 compacto; Isak como punta de lanza en transiciones",
    ),
    "BIH": _team("BIH", "UEFA_B",
        name="Bosnia-Herzegovina", group="F",
        xg_for=1.18, xg_against=1.28,
        form_index=59, offensive_rating=61, defensive_rating=60,
        tactical_note="Pljaca y Dzeko como referencias; físicos y directos",
    ),
    "CUW": _team("CUW", "CONCACAF_B",
        name="Curazao", group="D",
        xg_for=0.88, xg_against=1.52,
        form_index=42, offensive_rating=43, defensive_rating=44,
        tactical_note="Debut histórico; jugadores de diáspora holandesa, nivel muy inferior",
    ),
    "CPV": _team("CPV", "CAF_B",
        name="Cabo Verde", group="H",
        xg_for=1.05, xg_against=1.30,
        form_index=54, offensive_rating=55, defensive_rating=57,
        tactical_note="Sorpresa de la clasificación africana; organización defensiva como base",
    ),
    "JOR": _team("JOR", "AFC_B",
        name="Jordania", group="J",
        xg_for=1.02, xg_against=1.38,
        form_index=52, offensive_rating=53, defensive_rating=55,
        tactical_note="Primer mundial de su historia; bloque bajo y juego directo",
    ),
    "IRQ": _team("IRQ", "AFC_B",
        name="Irak", group="I",
        xg_for=1.05, xg_against=1.35,
        form_index=54, offensive_rating=55, defensive_rating=56,
        tactical_note="Retorno al Mundial; recursos físicos pero sin fineza técnica",
    ),
    "HAI": _team("HAI", "CONCACAF_B",
        name="Haití", group="L",
        xg_for=0.95, xg_against=1.45,
        form_index=45, offensive_rating=46, defensive_rating=47,
        tactical_note="Clasificación histórica; limitaciones técnicas notorias",
    ),
}


def get_team(code: str, raw_name: str = "") -> Dict[str, Any]:
    """
    Retorna datos del equipo. Intenta por código y luego por nombre crudo.
    Si no encuentra nada, devuelve perfil genérico (promedio del torneo).
    """
    if code in TEAMS:
        return TEAMS[code]

    # Intentar por nombre crudo (útil cuando la API devuelve equipos no mapeados)
    for t in TEAMS.values():
        if t.get("name", "").lower() == raw_name.lower():
            return t

    # Fallback: equipo desconocido con stats promedio
    fallback = {**_BASE, **CONF_DEFAULTS["UEFA_B"]}
    fallback["name"] = raw_name or code
    fallback["group"] = "?"
    fallback["tactical_note"] = f"Datos no disponibles para {raw_name or code}; usando promedio del torneo"
    return fallback


# ─── Partidos de demostración (cuando no hay API key) ──────────────────────
DEMO_MATCHES = [
    {
        "id": "E-MD3-A", "date": "2026-06-26",
        "team1": "JAP", "team2": "COR",
        "group": "E", "matchday": 3,
        "venue": "SoFi Stadium, Los Ángeles",
        "importance": "high",
        "context": "Japón ya clasificado como líder de grupo; Corea del Sur necesita al menos empatar",
        "bookmaker_odds": None, "live": False,
    },
    {
        "id": "E-MD3-B", "date": "2026-06-26",
        "team1": "CRO", "team2": "SUI",
        "group": "E", "matchday": 3,
        "venue": "Lumen Field, Seattle",
        "importance": "critical",
        "context": "Croacia eliminada si no gana; Suiza puede clasificar con empate",
        "bookmaker_odds": None, "live": False,
    },
    {
        "id": "D-MD3-A", "date": "2026-06-27",
        "team1": "MEX", "team2": "USA",
        "group": "D", "matchday": 3,
        "venue": "AT&T Stadium, Dallas",
        "importance": "critical",
        "context": "El Clásico CONCACAF — ambos necesitan resultado",
        "bookmaker_odds": None, "live": False,
    },
    {
        "id": "D-MD3-B", "date": "2026-06-27",
        "team1": "POR", "team2": "CAN",
        "group": "D", "matchday": 3,
        "venue": "BC Place, Vancouver",
        "importance": "medium",
        "context": "Portugal ya clasificado como 1ro; Canadá necesita ganar",
        "bookmaker_odds": None, "live": False,
    },
    {
        "id": "B-MD3-A", "date": "2026-06-28",
        "team1": "FRA", "team2": "MAR",
        "group": "B", "matchday": 3,
        "venue": "MetLife Stadium, Nueva York",
        "importance": "medium",
        "context": "Francia rotará titulares al estar clasificada; Marruecos lucha por el 2do puesto",
        "bookmaker_odds": None, "live": False,
    },
    {
        "id": "B-MD3-B", "date": "2026-06-28",
        "team1": "ESP", "team2": "SEN",
        "group": "B", "matchday": 3,
        "venue": "Rose Bowl, Pasadena",
        "importance": "medium",
        "context": "España clasificada; Senegal necesita ganar para tener opciones",
        "bookmaker_odds": None, "live": False,
    },
    {
        "id": "A-MD3-A", "date": "2026-06-29",
        "team1": "BRA", "team2": "COL",
        "group": "A", "matchday": 3,
        "venue": "Arrowhead Stadium, Kansas City",
        "importance": "high",
        "context": "Brasil clasificado como 1ro; Colombia necesita al menos empatar",
        "bookmaker_odds": None, "live": False,
    },
    {
        "id": "A-MD3-B", "date": "2026-06-29",
        "team1": "ARG", "team2": "ECU",
        "group": "A", "matchday": 3,
        "venue": "Gillette Stadium, Boston",
        "importance": "high",
        "context": "Argentina clasificada; Ecuador necesita ganar y que Colombia pierda",
        "bookmaker_odds": None, "live": False,
    },
    {
        "id": "C-MD3-A", "date": "2026-06-30",
        "team1": "ALE", "team2": "BEL",
        "group": "C", "matchday": 3,
        "venue": "Lincoln Financial Field, Filadelfia",
        "importance": "critical",
        "context": "Ambos equipos necesitan ganar para clasificar con seguridad",
        "bookmaker_odds": None, "live": False,
    },
    {
        "id": "C-MD3-B", "date": "2026-06-30",
        "team1": "ING", "team2": "PB",
        "group": "C", "matchday": 3,
        "venue": "Mercedes-Benz Stadium, Atlanta",
        "importance": "medium",
        "context": "Inglaterra clasificada como 1ro; Países Bajos necesita al menos empate",
        "bookmaker_odds": None, "live": False,
    },
]
